### ISSUE TITLE
Dot-setting fails for variables with a time dimension

### ISSUE THREAD

**Issue by jrising** [mimiframework/Mimi.jl#512]
If you try to set multiple elements of a variable, where one of the dimensions is time, you get a error from `dotview`. Here is a simple example:

```
@defcomp Simple begin
    region = Index()
    
    var = Variable(index=[time, region], unit="\$/yr")
    
    function run_timestep(p, v, d, t)
        v.var[t, :] .= 0
    end
end

model = Model()
set_dimension!(model, :time, collect(1:10))
set_dimension!(model, :region, ["Tropics", "Subtropics", "Temperates"])
add_comp!(model, Simple)
run(model)
```
produces the error:
```
ERROR: ArgumentError: invalid index: Mimi.FixedTimestep{1,1,10}(1) of type Mimi.FixedTimestep{1,1,10}
Stacktrace:
 [1] to_index(::Mimi.FixedTimestep{1,1,10}) at ./indices.jl:266
 [2] to_index(::Array{Union{Missing, Float64},2}, ::Mimi.FixedTimestep{1,1,10}) at ./indices.jl:247
 [3] to_indices at ./indices.jl:294 [inlined]
 [4] to_indices at ./indices.jl:290 [inlined]
 [5] view at ./subarray.jl:146 [inlined]
 [6] maybeview at ./views.jl:124 [inlined]
 [7] dotview at ./broadcast.jl:1074 [inlined]
 [8] dotview(::Mimi.TimestepArray{Mimi.FixedTimestep{1,1,LAST} where LAST,Union{Missing, Float64},2}, ::Mimi.FixedTimestep{1,1,10}, ::Function) at /Users/jrising/.julia/dev/Mimi/src/core/time.jl:359
 [9] run_timestep_Simple(::Mimi.ComponentInstanceParameters{NamedTuple{(),Tuple{}}}, ::Mimi.ComponentInstanceVariables{NamedTuple{(:var,),Tuple{Mimi.TimestepArray{Mimi.FixedTimestep{1,1,LAST} where LAST,Union{Missing, Float64},2}}}}, ::Mimi.DimDict, ::Mimi.FixedTimestep{1,1,10}) at /Users/jrising/.julia/dev/Mimi/src/core/defcomp.jl:7
 [10] run_timestep(::Mimi.ComponentInstance{Mimi.ComponentInstanceVariables{NamedTuple{(:var,),Tuple{Mimi.TimestepArray{Mimi.FixedTimestep{1,1,LAST} where LAST,Union{Missing, Float64},2}}}},Mimi.ComponentInstanceParameters{NamedTuple{(),Tuple{}}}}, ::Mimi.Clock{Mimi.FixedTimestep}) at /Users/jrising/.julia/dev/Mimi/src/core/instances.jl:264
 [11] _run_components(::Mimi.ModelInstance, ::Mimi.Clock{Mimi.FixedTimestep}, ::Array{Int64,1}, ::Array{Int64,1}, ::Array{Mimi.Clock{Mimi.FixedTimestep},1}) at /Users/jrising/.julia/dev/Mimi/src/core/instances.jl:277
 [12] run(::Mimi.ModelInstance, ::Int64, ::Nothing) at /Users/jrising/.julia/dev/Mimi/src/core/instances.jl:313
 [13] #run#114(::Int64, ::Nothing, ::Function, ::Model) at /Users/jrising/.julia/dev/Mimi/src/core/model.jl:399
 [14] run(::Model) at /Users/jrising/.julia/dev/Mimi/src/core/model.jl:390
 [15] top-level scope at none:0
```
You can do this with a variable that does not have a time dimension. It is possible to do this with a loop, but that gets messy for my use-case where I often have 4 dimensions.

**Comment by rjplevin** [comment]
Thanks, James for providing the test code. I just fixed this in the `dotview-fix` branch. Let me know if it works for you.

**Comment by jrising** [comment]
Sorry, your fix only works if the time dimension starts at 1. Above still fails with `collect(1:10)` replaced by `collect(21:30)`.

**Comment by rjplevin** [comment]
James, would you modify the short example so I can be sure to get it working properly?

**Comment by jrising** [comment]
Here you go:
```
@defcomp Simple begin
    region = Index()
    
    var = Variable(index=[time, region], unit="\$/yr")
    
    function run_timestep(p, v, d, t)
        v.var[t, :] .= 0
    end
end

model = Model()
set_dimension!(model, :time, collect(2015:2024))
set_dimension!(model, :region, ["Tropics", "Subtropics", "Temperates"])
add_comp!(model, Simple)
run(model)
```
produces:
```
ERROR: BoundsError: attempt to access 10×3 Array{Union{Missing, Float64},2} at index [2015, Base.Slice(Base.OneTo(3))]
Stacktrace:
 [1] throw_boundserror(::Array{Union{Missing, Float64},2}, ::Tuple{Int64,Base.Slice{Base.OneTo{Int64}}}) at ./abstractarray.jl:484
 [2] checkbounds at ./abstractarray.jl:449 [inlined]
 [3] view at ./subarray.jl:147 [inlined]
 [4] maybeview at ./views.jl:124 [inlined]
 [5] dotview at ./broadcast.jl:1074 [inlined]
 [6] dotview(::Mimi.TimestepArray{FixedTimestep{2015,1,LAST} where LAST,Union{Missing, Float64},2,1}, ::FixedTimestep{2015,1,2024}, ::Function) at /Users/jrising/.julia/dev/Mimi/src/core/time.jl:406
 [7] run_timestep_Simple(::Mimi.ComponentInstanceParameters{NamedTuple{(),Tuple{}}}, ::Mimi.ComponentInstanceVariables{NamedTuple{(:var,),Tuple{Mimi.TimestepArray{FixedTimestep{2015,1,LAST} where LAST,Union{Missing, Float64},2,1}}}}, ::Mimi.DimDict, ::FixedTimestep{2015,1,2024}) at /Users/jrising/.julia/dev/Mimi/src/core/defcomp.jl:7
 [8] run_timestep(::Mimi.ComponentInstance{Mimi.ComponentInstanceVariables{NamedTuple{(:var,),Tuple{Mimi.TimestepArray{FixedTimestep{2015,1,LAST} where LAST,Union{Missing, Float64},2,1}}}},Mimi.ComponentInstanceParameters{NamedTuple{(),Tuple{}}}}, ::Mimi.Clock{FixedTimestep}) at /Users/jrising/.julia/dev/Mimi/src/core/instances.jl:264
 [9] _run_components(::ModelInstance, ::Mimi.Clock{FixedTimestep}, ::Array{Int64,1}, ::Array{Int64,1}, ::Array{Mimi.Clock{FixedTimestep},1}) at /Users/jrising/.julia/dev/Mimi/src/core/instances.jl:277
 [10] run(::ModelInstance, ::Int64, ::Nothing) at /Users/jrising/.julia/dev/Mimi/src/core/instances.jl:313
 [11] #run#116(::Int64, ::Nothing, ::Function, ::Model) at /Users/jrising/.julia/dev/Mimi/src/core/model.jl:399
 [12] run(::Model) at /Users/jrising/.julia/dev/Mimi/src/core/model.jl:390
 [13] top-level scope at none:0
```

**Comment by rjplevin** [comment]
Sorry about that! I just pushed an update to that branch. Please try it again.

**Comment by jrising** [comment]
This seems to be working great. Thanks!
